/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JAndroidInstaller.UIComponent;

import JAndroidInstaller.PluginManager.JPluginInfo;
import JAndroidInstaller.PluginManager.JSearchPlugins;
import WSwingUILib.Component.Base.JImagePanel;
import WSwingUILib.Component.JMiddleContentPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wcss
 */
public class JAndroidUsefulToolPanel extends JMiddleContentPanel {

    ArrayList<JPluginInfo> plugins = null;

    /**
     * Creates new form JAndroidUsefulToolPanel
     */
    public JAndroidUsefulToolPanel() {
        initComponents();
        this.plToolContent.setBackground(Color.white);
        //this.plToolList.setBackground(Color.white);
    }

    /**
     * 载入
     */
    public void load() {
        plugins = JSearchPlugins.searchPlugins();
        System.out.println("有效插件：" + plugins.size() + "个");
        //JImagePanel panel = null;

        this.plToolContent.setPreferredSize(new Dimension(800, 516));
        int panelCount = 1 + (plugins.size() / 8);
        for (JPluginInfo jpi : plugins) {
            JToolListButton jlb = new JToolListButton();
            jlb.setPluginObj(jpi);
            plToolContent.add(jlb);
        }
        this.plToolContent.setPreferredSize(new Dimension(800, panelCount * 155));
        this.plToolContent.invalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        plToolContent = new WSwingUILib.Component.Base.JImagePanel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(834, 516));

        plToolContent.setFont(new java.awt.Font("文泉驿微米黑", 0, 14)); // NOI18N
        plToolContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(plToolContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private WSwingUILib.Component.Base.JImagePanel plToolContent;
    // End of variables declaration//GEN-END:variables
}
