/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JAndroidInstaller.UIComponent;

import JAndroidInstaller.AndroidDevice.USBDeviceInstaller;
import JAndroidInstaller.AndroidDevice.USBDeviceWorker;
import WSwingUILib.Component.JMiddleContentPanel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wcss
 */
public class JAndroidDeviceRestartPanel extends JMiddleContentPanel {

    JAPKInstallerUI parents = null;

    /**
     * Creates new form JAndroidDeviceRestartPanel
     */
    public JAndroidDeviceRestartPanel(JAPKInstallerUI par) {
        initComponents();
        parents = par;
        this.btnCheck.setButtonText("我已经准备好了，立即进入主界面！");
        this.plreadme.setReadmeInfo("<html>欢迎使用" + JAPKInstallerUI.config.getSoftCNName() + "！<br>1. 请用USB线将您的Android设备连接到电脑！ 2.请打开\"USB调试\"功能，如果已经打开，请关闭后重新打开！</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plreadme = new JAndroidInstaller.UIComponent.JReadmePanel();
        jImagePanel1 = new WSwingUILib.Component.Base.JImagePanel("/JAndroidInstaller/UIImage/deviceconnection.png");
        btnCheck = new WSwingUILib.Component.JUIButton();

        setLayout(null);
        add(plreadme);
        plreadme.setBounds(40, 400, 790, 92);

        javax.swing.GroupLayout jImagePanel1Layout = new javax.swing.GroupLayout(jImagePanel1);
        jImagePanel1.setLayout(jImagePanel1Layout);
        jImagePanel1Layout.setHorizontalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jImagePanel1Layout.setVerticalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        add(jImagePanel1);
        jImagePanel1.setBounds(130, 110, 620, 260);

        btnCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCheckLayout = new javax.swing.GroupLayout(btnCheck);
        btnCheck.setLayout(btnCheckLayout);
        btnCheckLayout.setHorizontalGroup(
            btnCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        btnCheckLayout.setVerticalGroup(
            btnCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(btnCheck);
        btnCheck.setBounds(630, 20, 230, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckMouseClicked
        try {
            // TODO add your handling code here:
            USBDeviceInstaller.restartAdbServer();
            if (USBDeviceWorker.isAndroidDeviceOnline()) 
            {
                plreadme.setReadmeInfo("设备状态正常！");
                parents.setStatusText("设备状态:已连接！");
                parents.showAllTabs();
            } else 
            {
                parents.setStatusText("对不起，未能检测到您的设备！");
            }
        } catch (Exception ex) {
            Logger.getLogger(JAndroidDeviceRestartPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheckMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private WSwingUILib.Component.JUIButton btnCheck;
    private WSwingUILib.Component.Base.JImagePanel jImagePanel1;
    private JAndroidInstaller.UIComponent.JReadmePanel plreadme;
    // End of variables declaration//GEN-END:variables
}
