/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JAndroidInstaller.UIComponent;

import JAndroidInstaller.PluginManager.JPluginInfo;
import JAndroidInstaller.PluginManager.JRunScriptFilters;
import WSwingUILib.Component.Base.JImagePanel;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author wcss
 */
public class JToolListButton extends JImagePanel {

    private JPluginInfo pluginObj;

    /**
     * Creates new form JToolListItem
     */
    public JToolListButton() {
        initComponents();
        this.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plLogo = new WSwingUILib.Component.Base.JImagePanel();
        lblName = new javax.swing.JLabel();

        setFont(new java.awt.Font("文泉驿微米黑", 0, 14)); // NOI18N

        javax.swing.GroupLayout plLogoLayout = new javax.swing.GroupLayout(plLogo);
        plLogo.setLayout(plLogoLayout);
        plLogoLayout.setHorizontalGroup(
            plLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        plLogoLayout.setVerticalGroup(
            plLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        lblName.setFont(new java.awt.Font("文泉驿微米黑", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblName;
    private WSwingUILib.Component.Base.JImagePanel plLogo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pluginObj
     */
    public JPluginInfo getPluginObj() {
        return pluginObj;
    }

    /**
     * @param pluginObj the pluginObj to set
     */
    public void setPluginObj(JPluginInfo pluginObj) {
        this.pluginObj = pluginObj;
        
        this.plLogo.setImageIcon(new ImageIcon(pluginObj.getPluginWorkspace() + "/image.png"),true);
        if (pluginObj.getPluginName().length() <= 6)
        {
            this.lblName.setText(pluginObj.getPluginName());
        }else
        {
            String name = JRunScriptFilters.replaceStr(pluginObj.getPluginName(),"[br]","<br>");
            this.lblName.setText("<html>" + name + "</html>");
        }
    }
}
