/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JAndroidInstaller.ROMLists;

import JAndroidInstaller.UIComponent.JAndroidRomList;
import WSwingUILib.Component.Base.JImagePanel;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author wcss
 */
public class JRomListItem extends JImagePanel {

    private JRomRecordEntry localRecord;
    private JAndroidRomList parents = null;

    /**
     * Creates new form JRomListItem
     */
    public JRomListItem() {
        initComponents();
    }

    /**
     * Creates new form JRomListItem
     */
    public JRomListItem(JRomRecordEntry record, JAndroidRomList par) {
        initComponents();
        this.parents = par;
        this.setSize(640, 140);
        this.setLocalRecord(record);
        this.lblName.setText(this.getLocalRecord().getRomName());
        this.lblDate.setText("发布日期：" + this.getLocalRecord().getRomMakeDate());
        this.lblMaker.setText("发布者：" + this.getLocalRecord().getRomMaker());
        if (this.getLocalRecord().getRomInfo().contains("[br]")) {
            this.lblInfo.setText("<html>" + this.getLocalRecord().getRomInfo().replace("[br]", "<br>") + "</html>");
        } else {
            this.lblInfo.setText(this.getLocalRecord().getRomInfo());
        }

        if (this.getLocalRecord().getRomIcon() != null && new File(this.getLocalRecord().getRomIcon()).exists()) {
            try {
                this.plImage.setImageIcon(new ImageIcon(ImageIO.read(new FileInputStream(this.getLocalRecord().getRomIcon()))), Boolean.TRUE);
            } catch (IOException ex) {
                Logger.getLogger(JRomListItem.class.getName()).log(Level.SEVERE, null, ex);
                this.plImage.setImageIconFromResource("/JAndroidInstaller/UIImage/romitem.png", true);
            }
        } else {
            this.plImage.setImageIconFromResource("/JAndroidInstaller/UIImage/romitem.png", true);
        }

        if (this.getLocalRecord().getRomFile() != null && !this.getLocalRecord().getRomFile().isEmpty()) {
            if (this.getLocalRecord().getRomFile().startsWith("http:")) {
                this.btnDownload.setEnabled(true);
                if (this.parents.existRomInQueue(this.getLocalRecord().getRomFile())) {
                    this.btnDownload.setButtonText(">>停止下载");
                } else {
                    this.btnDownload.setButtonText(">>下载固件");
                }
            } else {
                this.btnDownload.setButtonText("未开放下载");
                this.btnDownload.setEnabled(false);
            }
        } else {
            this.btnDownload.setButtonText("未开放下载");
            this.btnDownload.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        plTemp = new WSwingUILib.Component.Base.JImagePanel();
        plImage = new WSwingUILib.Component.Base.JImagePanel();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnDownload = new WSwingUILib.Component.JUIButton();
        lblMaker = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        plTemp.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout plImageLayout = new javax.swing.GroupLayout(plImage);
        plImage.setLayout(plImageLayout);
        plImageLayout.setHorizontalGroup(
            plImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        plImageLayout.setVerticalGroup(
            plImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout plTempLayout = new javax.swing.GroupLayout(plTemp);
        plTemp.setLayout(plTempLayout);
        plTempLayout.setHorizontalGroup(
            plTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plTempLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(plImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        plTempLayout.setVerticalGroup(
            plTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plTempLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(plImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        lblName.setFont(new java.awt.Font("文泉驿微米黑", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 255));
        lblName.setText("jLabel1");

        lblDate.setFont(new java.awt.Font("文泉驿微米黑", 0, 14)); // NOI18N
        lblDate.setText("jLabel2");

        lblInfo.setFont(new java.awt.Font("文泉驿微米黑", 0, 14)); // NOI18N
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfo.setText("jLabel3");
        lblInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnDownload.setButtonText(">>下载固件");
        btnDownload.setFont(new java.awt.Font("文泉驿微米黑", 1, 16)); // NOI18N
        btnDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDownloadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnDownloadLayout = new javax.swing.GroupLayout(btnDownload);
        btnDownload.setLayout(btnDownloadLayout);
        btnDownloadLayout.setHorizontalGroup(
            btnDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        btnDownloadLayout.setVerticalGroup(
            btnDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        lblMaker.setFont(new java.awt.Font("文泉驿微米黑", 0, 14)); // NOI18N
        lblMaker.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(plTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(lblMaker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(plTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDownloadMouseClicked
        // TODO add your handling code here:
        if (this.btnDownload.getButtonText().contains("停止下载"))
        {
            this.parents.removeRomFromQueue(this.getLocalRecord().getRomFile());
        } else {
            if (this.getLocalRecord().getRomFile() != null && !this.getLocalRecord().getRomFile().isEmpty()) {
                if (this.getLocalRecord().getRomFile().startsWith("http:")) {
                    this.parents.downloadRomFile(this.getLocalRecord().getRomFile());
                } else {
                    this.parents.printInfo("对不起，此固件没有开放下载！");
                }
            } else {
                this.parents.printInfo("对不起，此固件没有开放下载！");
            }
        }
    }//GEN-LAST:event_btnDownloadMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private WSwingUILib.Component.JUIButton btnDownload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblMaker;
    private javax.swing.JLabel lblName;
    private WSwingUILib.Component.Base.JImagePanel plImage;
    private WSwingUILib.Component.Base.JImagePanel plTemp;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the localRecord
     */
    public JRomRecordEntry getLocalRecord() {
        return localRecord;
    }

    /**
     * @param localRecord the localRecord to set
     */
    public void setLocalRecord(JRomRecordEntry localRecord) {
        this.localRecord = localRecord;
    }
}
