/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JAndroidInstaller.InstallerUI;

import JAndroidInstaller.AndroidDevice.USBDeviceWorker;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wcss
 */
public class JAPKInstallerCopyFiles extends javax.swing.JFrame implements Runnable {

    private JAPKInstallerMainUI main = null;
    private File[] fileList = null;
    private String destPath = "";

    /**
     * Creates new form JAPKInstallerCopyFiles
     */
    public JAPKInstallerCopyFiles(JAPKInstallerMainUI parent, File[] source, String dest) {
        initComponents();
        this.setLocationRelativeTo(null);
        main = parent;
        fileList = source;
        destPath = dest;

        Thread tt = new Thread(this);
        tt.setDaemon(true);
        tt.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("正在复制文件，请稍后......");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        if (fileList.length > 0) {
            int current = 0;
            progress.setMaximum(fileList.length);
            current = 1;

            for (File f : fileList) {
                progress.setValue(current);
                
                try {
                    USBDeviceWorker.copyToSdcard(f.getAbsolutePath(), this.destPath + "/" + f.getName());
                } catch (Exception ex) {
                    Logger.getLogger(JAPKInstallerCopyFiles.class.getName()).log(Level.SEVERE, null, ex);
                }

                current++;
            }
        }

        main.uploadFileLists();
        this.dispose();
    }
}
