/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JAndroidInstaller.InstallerUI;

import JAndroidInstaller.AndroidDevice.USBDeviceChecker;
import JAndroidInstaller.AndroidDevice.USBDeviceInstaller;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wcss
 */
public class JAPKInstallerDriverUI extends javax.swing.JFrame {

    private int currentStepIndex = 0;
    private ArrayList<String> firstChecks = null;
    private ArrayList<String> secondChecks = null;

    /**
     * Creates new form JAPKInstallerDriverUI
     */
    public JAPKInstallerDriverUI() {
        initComponents();
        this.setTitle("APK安装器ADB驱动配置");
        this.setLocationRelativeTo(null);
        currentStepIndex = 1;
        this.lblStep1Flag.setText("<---");
        this.lblStep2Flag.setText("");
        this.lblStep3Flag.setText("");
    }

    public void showStepHint(int index) {
        this.lblStep1Flag.setText("");
        this.lblStep2Flag.setText("");
        this.lblStep3Flag.setText("");
        switch (index) {
            case 1: {
                lblStep1Flag.setText("<---");
            }
            break;
            case 2: {
                lblStep2Flag.setText("<---");
            }
            break;
            case 3: {
                lblStep3Flag.setText("<---");
            }
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStep2 = new javax.swing.JLabel();
        lblStep3 = new javax.swing.JLabel();
        lblStep1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProductID = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblStep1Flag = new javax.swing.JLabel();
        lblStep2Flag = new javax.swing.JLabel();
        lblStep3Flag = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStep2.setText("第二步，插上手机数据线并点击下一步按钮。");

        lblStep3.setText("第三步，手机型号检查完成。");

        lblStep1.setText("第一步，拔掉手机数据线并点击下一步按钮。");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Android设备信息"));

        jLabel1.setText("厂商ID：");

        lblProductID.setText("未知");

        lblProductName.setText("未知");

        jLabel4.setText("厂商名称：");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblProductName))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblProductID)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnNext.setText("下一步");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblStep1Flag.setText("jLabel1");

        lblStep2Flag.setText("jLabel2");

        lblStep3Flag.setText("jLabel3");

        jLabel2.setText("<html>注：本程序在进行文件管理时，需要Android端有busybox的支持！<br>\n如果你在设备上使用过网页式的android管理软件，那么它可能会占用adb通道，这样的情况下，请关闭\"USB调试\"功能后重新打开!\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblStep3Flag))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStep2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblStep2Flag))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStep1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblStep1Flag))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnNext)
                                .addGap(100, 100, 100)
                                .addComponent(btnExit)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStep1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStep1Flag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStep2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStep2Flag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStep3Flag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if (currentStepIndex == 1) {
            try {
                firstChecks = USBDeviceChecker.getDeviceData();
            } catch (Exception ex) {
                Logger.getLogger(JAPKInstallerDriverUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (currentStepIndex == 2) {
            try {
                secondChecks = USBDeviceChecker.getDeviceData();
            } catch (Exception ex) {
                Logger.getLogger(JAPKInstallerDriverUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (secondChecks != null && firstChecks != null) {
                for (String sss : firstChecks) {
                    if (secondChecks.contains(sss)) {
                        secondChecks.remove(sss);
                    }
                }

                if (secondChecks.size() >= 1) {
                    String[] teams = secondChecks.get(0).split(":");
                    this.lblProductID.setText(teams[0].trim());
                    HashMap<String, String> table = USBDeviceChecker.getMakerTable();
                    if (table.containsKey(teams[0].trim())) {
                        this.lblProductName.setText(table.get(teams[0].trim()));
                    } else {
                        this.lblProductName.setText("未知");
                    }
                }
            }
        } else if (currentStepIndex == 3) {
            if (secondChecks != null && firstChecks != null) {
                if (secondChecks.size() >= 1) {
                    String[] teams = secondChecks.get(0).split(":");
                    try {
                        Boolean result = USBDeviceInstaller.installUsbDevice(teams[0].trim());
                        if (result)
                        {
                            javax.swing.JOptionPane.showMessageDialog(null, "Adb驱动配置完成！");
                        }else
                        {
                           USBDeviceInstaller.restartAdbServer();
                           javax.swing.JOptionPane.showMessageDialog(null, "Adb服务重启完成！");
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(JAPKInstallerDriverUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "检测失败！请关闭程序后重新开始！");
                }
            }
        } else {
            JAPKInstallerMainUI.startMainUI(JAPKInstallerMainUI.currentArgs);
            this.dispose();
        }

        currentStepIndex++;
        showStepHint(currentStepIndex);
        if (currentStepIndex == 4) {
            this.btnNext.setText("完成");
        } else if (currentStepIndex == 3) {
            this.btnNext.setText("安装");
        }
    }//GEN-LAST:event_btnNextActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblStep1;
    private javax.swing.JLabel lblStep1Flag;
    private javax.swing.JLabel lblStep2;
    private javax.swing.JLabel lblStep2Flag;
    private javax.swing.JLabel lblStep3;
    private javax.swing.JLabel lblStep3Flag;
    // End of variables declaration//GEN-END:variables
}
